### ISSUE TITLE
多dex时候无法成功

### ISSUE THREAD

**Issue by jinkailong888** [279154451/AESApk#1]
单个dex文件可以处理成功，如果apk是多dex时候启动就会崩溃，有解决方案吗？

**Comment by jinkailong888** [comment]
java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/com.example.protectapp-j0D7Z2U50jBej9RQltFFVg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.protectapp-j0D7Z2U50jBej9RQltFFVg==/lib/arm64, /data/app/com.example.protectapp-j0D7Z2U50jBej9RQltFFVg==/base.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:238)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:778)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:857)
        at android.app.LoadedApk.getResources(LoadedApk.java:1092)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2481)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6202)
        at android.app.ActivityThread.access$1300(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1873)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7223)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)
2020-04-10 10:01:08.090 5326-5326/? E/System: Unable to load dex file: /data/user/0/com.example.protectapp/app_fake_apk/app/classes2.dex
2020-04-10 10:01:08.092 5326-5326/? E/System: java.io.IOException: No original dex files found for dex location /data/user/0/com.example.protectapp/app_fake_apk/app/classes2.dex
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:143)
        at dalvik.system.DexFile.loadDex(DexFile.java:202)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:397)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:344)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:321)
        at dalvik.system.DexPathList.makePathElements(DexPathList.java:443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.example.mylibrary.ShellApplication.makePathElements(ShellApplication.java:292)
        at com.example.mylibrary.ShellApplication.access$200(ShellApplication.java:28)
        at com.example.mylibrary.ShellApplication$V19.install(ShellApplication.java:198)
        at com.example.mylibrary.ShellApplication$V19.access$000(ShellApplication.java:173)
        at com.example.mylibrary.ShellApplication.attachBaseContext(ShellApplication.java:62)
        at android.app.Application.attach(Application.java:216)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1122)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6295)
        at android.app.ActivityThread.access$1300(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1873)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7223)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)
2020-04-10 10:01:08.093 5326-5326/? E/System: Unable to load dex file: /data/user/0/com.example.protectapp/app_fake_apk/app/classes3.dex
2020-04-10 10:01:08.096 5326-5326/? E/System: java.io.IOException: No original dex files found for dex location /data/user/0/com.example.protectapp/app_fake_apk/app/classes3.dex
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:143)
        at dalvik.system.DexFile.loadDex(DexFile.java:202)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:397)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:344)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:321)
        at dalvik.system.DexPathList.makePathElements(DexPathList.java:443)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.example.mylibrary.ShellApplication.makePathElements(ShellApplication.java:292)
        at com.example.mylibrary.ShellApplication.access$200(ShellApplication.java:28)
        at com.example.mylibrary.ShellApplication$V19.install(ShellApplication.java:198)
        at com.example.mylibrary.ShellApplication$V19.access$000(ShellApplication.java:173)
        at com.example.mylibrary.ShellApplication.attachBaseContext(ShellApplication.java:62)
        at android.app.Application.attach(Application.java:216)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1122)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6295)
        at android.app.ActivityThread.access$1300(ActivityThread.java:229)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1873)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:226)
        at android.app.ActivityThread.main(ActivityThread.java:7223)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)
2020-04-10 10:01:08.122 5326-5326/? E/AndroidRuntime: FATAL EXCEPTION: main
